# Generated by Django 3.2.16 on 2022-10-18 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secondapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='people',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name1', models.CharField(max_length=250)),
                ('image', models.ImageField(upload_to='pictures')),
                ('desc', models.TextField()),
            ],
        ),
    ]
